### PR TITLE
Change member list source page

### PR DESCRIPTION
**Pull request by ondenman**
This is in preparation of scraping the previous term.

The 2016 members are also listed on a page that is different from the one currently scraped.

Using this as the 2016 member source would be beneficial as the previous term members, which will be scaped in a forthcoming PR, are listed on a page with an identical layout.

MembersPage has been adapted to scrape the new layout. The before and after outputs should be the same.

The term pages are here: http://house.gov.by/ru/sozyvy-ru/

Part of: https://github.com/everypolitician/everypolitician-data/issues/26546

### CODE REVIEW

**Review by tmtmtmtm — CHANGES_REQUESTED** [review]
I'm afraid I can't understand what this PR is doing, or why. I can't even really tell whether it's meant to produce the same results as before, or different ones.

**Comment by ondenman** [comment]
@tmtmtmtm I've updated the description to give a better explanation of this PR.

**Review by tmtmtmtm — CHANGES_REQUESTED** [review]
Based on the new PR description (although I think an "also" in the middle of "The 2016 members are listed on a page that is different…" would help even more), I think you need to split this PR in two.

Adding tests in the middle of a PR that's expected to produce no difference in result makes it much more difficult to see that. I'd suggest adding some tests first (and turning on check-fail), and then making this change  in a separate PR after that.

**Comment by ondenman** [comment]
@tmtmtmtm I've paired the PR down to just the change and the test.

**Review by tmtmtmtm — APPROVED** [review]

**Pull request merged**
